version: 0.0
os: windows
files:
  - source: \
    destination: C:\temp\WebApp\MusicWorld
  
hooks:
  BeforeInstall:
    - location: .\StageArtifact.ps1
      timeout: 3600
    - location: .\CreateWebSite.ps1
      timeout: 3600
    - location: .\temp2.ps1
      timeout: 3600

  AfterInstall:
    - location: .\temp3.ps1
      timeout: 500
  