version: 0.0
os: windows
files:
  - source: \
    destination: C:\inetpub\wwwroot\MusicWorld
  
hooks:
  BeforeInstall: 
    - location: .\temp2.ps1
      timeout: 3600

  AfterInstall:
    - location: .\CreateWebSite.ps1
      timeout: 3600
    - location: .\temp3.ps1
      timeout: 500
  