version: 0.0
os: windows
files:
  - source: \
    destination: C:\temp\WebApp\lr-api-v1
  
hooks:
  BeforeInstall: 
    - location: .\temp2.ps1
      timeout: 3600

  AfterInstall:
    - location: .\StageArtifact.ps1
      timeout: 3600
    - location: .\CreateWebSite.ps1
      timeout: 3600
  